//common reducer action types
export const START_APP = "START_APP";
export const UPDATE_IS_FETCHING = "UPDATE_IS_FETCHING";
export const TOKEN_INFO = "TOKEN_INFO";

/* #region  AGENCY */

export const FETCHING_AGENCY_ATTRIBUTE = "FETCHING_AGENCY_ATTRIBUTE";
export const FETCHING_AGENCY_ATTRIBUTE_SUCCESS = "FETCHING_AGENCY_ATTRIBUTE_SUCCESS";
export const FETCHING_AGENCY_ATTRIBUTE_FAILED = "FETCHING_AGENCY_ATTRIBUTE_SUCCESS";

export const FETCHING_AGENCY_LINK_ATTRIBUTE = "FETCHING_AGENCY_LINK_ATTRIBUTE";
export const FETCHING_AGENCY_LINK_ATTRIBUTE_SUCCESS = "FETCHING_AGENCY_LINK_ATTRIBUTE_SUCCESS";
export const FETCHING_AGENCY_LINK_ATTRIBUTE_FAILED = "FETCHING_AGENCY_ATTRIBUTE_FAILED";

export const FETCHING_AGENCY_ENTITY_TYPES_SUCCESS = "FETCHING_AGENCY_ENTITY_TYPES_SUCCESS";

/* #endregion */

/* #region PERSON  */
export const FETCHING_AGENCY_PERSONS = "FETCHING_AGENCY_PERSONS";
export const FETCHING_AGENCY_PERSONS_SUCCESS = "FETCHING_AGENCY_PERSONS_SUCCESS";
export const FETCHING_AGENCY_PERSONS_FAILED = "FETCHING_AGENCY_PERSONS_FAILED";

export const SAVING_AGENCY_PERSONS = "SAVING_AGENCY_PERSONS";
export const SAVING_AGENCY_PERSONS_SUCCESS = "SAVING_AGENCY_PERSONS_SUCCESS";
export const SAVING_AGENCY_PERSONS_FAILED = "SAVING_AGENCY_PERSONS_FAILED";

export const SAVING_AGENCY_PERSONS_VEHICLE = "SAVING_AGENCY_PERSONS_VEHICLE";
export const SAVING_AGENCY_PERSONS_VEHICLE_SUCCESS = "SAVING_AGENCY_PERSONS_VEHICLE_SUCCESS";
export const SAVING_AGENCY_PERSONS_VEHICLE_FAILED = "SAVING_AGENCY_PERSONS_VEHICLE_FAILED";
/* #endregion */

export const SAVING_AGENCY_REPORT = "SAVING_AGENCY_REPORT";
export const SAVING_AGENCY_REPORT_SUCCESS = "SAVING_AGENCY_REPORT_SUCCESS";
export const SAVING_AGENCY_REPORT_FAILED = "SAVING_AGENCY_REPORT_FAILED";

export const FETCHING_AGENCY_GANG_PROFILE = "FETCHING_AGENCY_GANG_PROFILE";
export const FETCHING_AGENCY_GANG_PROFILE_SUCCESS = "FETCHING_AGENCY_GANG_PROFILE_SUCCESS";
export const FETCHING_AGENCY_GANG_PROFILE_FAILED = "FETCHING_AGENCY_GANG_PROFILE_FAILED";

export const SAVING_AGENCY_GANG = "SAVING_AGENCY_GANG";
export const SAVING_AGENCY_GANG_SUCCESS = "SAVING_AGENCY_GANG_SUCCESS";
export const SAVING_AGENCY_GANG_FAILED = "SAVING_AGENCY_GANG_FAILED";

export const SAVING_INTEL_REPORT = "SAVING_INTEL_REPORT";
export const SAVING_INTEL_REPORT_SUCCESS = "SAVING_INTEL_REPORT_SUCCESS";
export const SAVING_INTEL_REPORT_FAILED = "SAVING_INTEL_REPORT_FAILED";

export const FETCHING_AGENCY_INTEL_PROFILE = "FETCHING_AGENCY_INTEL_PROFILE";
export const FETCHING_AGENCY_INTEL_PROFILE_SUCCESS = "FETCHING_AGENCY_INTEL_PROFILE_SUCCESS";
export const FETCHING_AGENCY_INTEL_PROFILE_FAILED = "FETCHING_AGENCY_INTEL_PROFILE_FAILED";

export const FETCHING_AGENCY_USER_PROFILE = "FETCHING_AGENCY_USER_PROFILE";
export const FETCHING_AGENCY_USER_PROFILE_SUCCESS = "FETCHING_AGENCY_USER_PROFILE_SUCCESS";
export const FETCHING_AGENCY_USER_PROFILE_FAILED = "FETCHING_AGENCY_USER_PROFILE_FAILED";

export const FETCHING_AGENCY_USER_DETAILS = "FETCHING_AGENCY_USER_DETAILS";

export const AGENCY_THEME = "AGENCY_THEME";
export const AGENCY_USER_PROFILE_PIC = "AGENCY_USER_PROFILE_PIC";
export const AGENCY_LOGO = "AGENCY_LOGO";
export const AGENCY_NAME="AGENCY_NAME";


export const DB_DATA="DB_DATA"